### ISSUE TITLE
Tip: `box-sizing: border-box`

### ISSUE THREAD

**Issue by 0xZakk** [aiyentam/pineapple#1]
I love `box-sizing: border-box`, I usually apply it to every element with this snippet:

```css
* {
  box-sizing: border-box;
}
```

https://github.com/aiyentam/pineapple/blob/491537d6ac221cba4bd8919e86483b6cb6ffac5b/css/main.css#L29
